/** Canonical probe bodies used when Dexter AI verifier sends an empty POST body */
export const VERIFY_EXAMPLES: Record<string, unknown> = {
  "/api/x402/proxy": {
    agentId: "dexter-verifier-probe",
    walletAddress: "9c7tE587KpGYBjiNQrjw3nGvxQHhSYKU4Ba6WRgQsHkt",
    targetUrl: "https://api.myceliasignal.com/oracle/price/eth/usd",
    estimatedCostUsdc: 0.05,
    policy: { dailyCapUsdc: 10, perCallCapUsdc: 0.5 },
    issueAttestation: true,
  },
  "/api/mpp/session": {
    action: "open",
    expectedCalls: 25,
    avgPricePerCallUsdc: 0.03,
    chain: "solana",
    agentId: "dexter-verifier-probe",
  },
  "/api/attestation/issue": {
    agentId: "dexter-verifier-probe",
    walletAddress: "9c7tE587KpGYBjiNQrjw3nGvxQHhSYKU4Ba6WRgQsHkt",
    targetUrl: "https://api.myceliasignal.com/oracle/price/eth/usd",
    estimatedCostUsdc: 0.03,
    policy: { dailyCapUsdc: 10, perCallCapUsdc: 0.5 },
  },
  "/api/attestation/verify": {
    attestationId: "att_verifier_probe_example",
  },
  "/api/guard/pre-x402": {
    agentId: "dexter-verifier-probe",
    walletAddress: "9c7tE587KpGYBjiNQrjw3nGvxQHhSYKU4Ba6WRgQsHkt",
    targetUrl: "https://api.myceliasignal.com/oracle/price/eth/usd",
    estimatedCostUsdc: 0.05,
    network: "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp",
    policy: { dailyCapUsdc: 10, perCallCapUsdc: 0.5, allowedHosts: ["myceliasignal.com"] },
  },
  "/api/pipeline/execute": {
    agentId: "dexter-verifier-probe",
    walletAddress: "9c7tE587KpGYBjiNQrjw3nGvxQHhSYKU4Ba6WRgQsHkt",
    targetUrl: "https://api.myceliasignal.com/oracle/price/eth/usd",
    estimatedCostUsdc: 0.05,
    network: "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp",
    policy: { dailyCapUsdc: 10, perCallCapUsdc: 0.5, allowedHosts: ["myceliasignal.com"] },
    task: "ETH oracle with guard and marketplace routing under one dollar",
    maxBudgetUsdc: 1,
    marketplaceQuery: "ETH USD spot price oracle",
    preferNetwork: "solana",
  },
  "/api/payment-intent/compile": {
    task: "Verify spend policy for ETH oracle call under one dollar budget",
    maxBudgetUsdc: 1,
    agentId: "dexter-verifier-probe",
    externalCallEstimateUsdc: 0.05,
  },
  "/api/facilitator/failover": {
    targetUrl: "https://api.myceliasignal.com/oracle/price/eth/usd",
    preferNetwork: "solana",
    fastProbe: true,
  },
  "/api/mpp/session-plan": {
    action: "estimate",
    expectedCalls: 25,
    avgPricePerCallUsdc: 0.03,
  },
  "/api/spend-governor/check": {
    agentId: "dexter-verifier-probe",
    estimatedCostUsdc: 0.03,
    targetUrl: "https://api.myceliasignal.com/oracle/price/eth/usd",
    network: "solana:5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp",
    policy: { dailyCapUsdc: 10, perCallCapUsdc: 0.5, allowedHosts: ["myceliasignal.com"] },
  },
  "/api/identity-gate/check": {
    walletAddress: "9c7tE587KpGYBjiNQrjw3nGvxQHhSYKU4Ba6WRgQsHkt",
    maxTierSpendUsdc: 10,
  },
  "/api/risk-gate/scan": {
    targetUrl: "https://api.myceliasignal.com/oracle/price/eth/usd",
    estimatedCostUsdc: 0.05,
    policy: { dailyCapUsdc: 10, perCallCapUsdc: 0.5 },
  },
  "/api/router/route": {
    query: "ETH USD spot price oracle",
    preferNetwork: "solana",
    maxPriceUsdc: 0.1,
    skipProbes: true,
  },
  "/api/research/brief": {
    topic: "Ethereum network fees today",
    includePrice: true,
    fastProbe: true,
  },
  "/api/receipt-auditor/verify": {
    network: "eip155:8453",
    expectedAmountUsdc: 0.05,
    transactionHash:
      "0x0000000000000000000000000000000000000000000000000000000000000001",
    settlement: {
      transaction:
        "0x0000000000000000000000000000000000000000000000000000000000000001",
      amountUsdc: 0.05,
      network: "eip155:8453",
      payer: "0x0000000000000000000000000000000000000001",
    },
  },
  "/api/refund-arbiter/evaluate": {
    verificationScore: 85,
    responseEmpty: false,
    responseGeneric: false,
    endpointReachable: true,
  },
  "/api/budget-allocator/run": {
    fleetId: "verifier-fleet",
    poolRemainingUsdc: 1,
    agents: [
      { agentId: "a1", priority: 10, requestedUsdc: 0.2, dailyRemainingUsdc: 5 },
    ],
  },
  "/api/settlement-graph/next": {
    lastEndpointPath: "/api/spend-governor/check",
    lastTopic: "agent spend policy",
  },
  "/api/quality-monitor/probe": {
    urls: ["https://x402trustlayer.xyz/health"],
  },
  "/api/evidence-locker/export": {
    organizationId: "verifier-org",
    records: [
      {
        endpoint: "/api/spend-governor/check",
        amountUsdc: 0.03,
        network: "solana",
        timestamp: new Date().toISOString(),
      },
    ],
  },
  "/api/agent-escrow": {
    action: "create",
    payerAgentId: "verifier-payer",
    payeeAgentId: "verifier-payee",
    amountUsdc: 0.05,
    releaseCondition: "receipt-auditor valid:true",
  },
  "/api/market/buy-advisor": {
    intent: "ETH USD spot price oracle for trading bot",
    agentId: "dexter-verifier-probe",
    walletAddress: "9c7tE587KpGYBjiNQrjw3nGvxQHhSYKU4Ba6WRgQsHkt",
    preferNetwork: "eip155:8453",
    maxPriceUsdc: 0.15,
    expectedCalls: 12,
    policy: { dailyCapUsdc: 10, perCallCapUsdc: 0.5, allowedHosts: ["myceliasignal.com", "dexter.cash"] },
    dryRunTarget: true,
  },
  "/api/seller/audition-coach": {
    origin: "https://x402trustlayer.xyz",
    maxRoutes: 3,
  },
  "/api/merchant-trust/score": {
    host: "api.myceliasignal.com",
    targetUrl: "https://api.myceliasignal.com/oracle/price/eth/usd",
    observedTxns: 54,
    observedVolumeUsdc: 1.76,
    washTradePct: 17,
    verifiedResources: 44,
    totalResources: 91,
    p50LatencyMs: 1200,
    probe: false,
  },
  "/api/mandate/compile": {
    principal: "cardholder:dexter-verifier",
    agentId: "dexter-verifier-probe",
    intent: "Buy ETH/USD oracle data for a trading bot, under $1 per call, daily $10 cap",
    maxPerTxUsdc: 0.5,
    dailyCapUsdc: 10,
    allowedMerchants: ["myceliasignal.com", "dexter.cash"],
    allowedCategories: ["market-data", "oracle"],
    allowedRails: ["base-x402", "solana-x402", "visa-cli"],
    ttlMinutes: 1440,
  },
  "/api/mandate/verify": {
    mandateId: "mdt_verifier_probe_example",
    proposed: {
      amountUsdc: 0.05,
      merchant: "api.myceliasignal.com",
      category: "oracle",
      rail: "base-x402",
    },
  },
  "/api/rail-optimizer/route": {
    amountUsdc: 1.5,
    disputable: true,
    latencySensitive: false,
    expectedCalls: 1,
  },
  "/api/compliance/ledger": {
    organizationId: "verifier-org",
    period: "2026-05",
    records: [
      {
        merchant: "api.myceliasignal.com",
        amountUsdc: 0.05,
        rail: "base-x402",
        network: "eip155:8453",
        category: "oracle",
        agentId: "dexter-verifier-probe",
        transactionHash: "0x0000000000000000000000000000000000000000000000000000000000000001",
        timestamp: new Date().toISOString(),
      },
    ],
    policy: { monthlyCapUsdc: 1000, perMerchantCapUsdc: 500, requireTxHash: true },
  },
  "/api/dispute/resolve": {
    rail: "visa-cli",
    merchant: "api.myceliasignal.com",
    amountUsdc: 1.0,
    reason: "non_delivery",
    evidence: { actualResponseEmpty: true, receiptValid: false },
  },
  "/api/quality-escrow/settle": {
    action: "settle",
    payerAgentId: "dexter-verifier-probe",
    payeeMerchant: "api.myceliasignal.com",
    amountUsdc: 0.05,
    releaseThreshold: 70,
    expectedProfile: { requiredKeys: ["price", "symbol"], minLengthBytes: 16, forbidEmpty: true },
    actualResponse: { bodyKeys: ["price", "symbol", "ts"], byteLength: 64, empty: false },
  },
};
