import { pricing } from "../config.js";
import { listProtocolEndpoints } from "../routes-protocol.js";

export function listEndpoints() {
  return [
    { path: "POST /api/a2a/execute", price: `$${pricing.a2aExecute}`, tier: "killer" },
    { path: "POST /api/bedrock/preflight", price: `$${pricing.bedrockPreflight}`, tier: "orchestration" },
    { path: "POST /api/market/buy-advisor", price: `$${pricing.marketBuyAdvisor}`, tier: "killer" },
    { path: "POST /api/seller/audition-coach", price: `$${pricing.auditionCoach}`, tier: "killer" },
    { path: "POST /api/x402/proxy", price: `$${pricing.x402Proxy}`, tier: "killer" },
    { path: "POST /api/mpp/session", price: `$${pricing.mppSessionV2}`, tier: "killer" },
    { path: "POST /api/attestation/issue", price: `$${pricing.attestationIssue}`, tier: "killer" },
    { path: "POST /api/attestation/verify", price: `$${pricing.attestationVerify}`, tier: "killer" },
    { path: "GET /api/attestation/registry", price: `$${pricing.trustRegistry}`, tier: "killer" },
    { path: "POST /api/guard/pre-x402", price: `$${pricing.preX402Guard}`, tier: "bundle" },
    { path: "POST /api/agent/verify", price: `$${pricing.agentVerify}`, tier: "identity" },
    { path: "POST /api/pipeline/execute", price: `$${pricing.pipelineExecute}`, tier: "bundle" },
    { path: "POST /api/facilitator/failover", price: `$${pricing.facilitatorFailover}`, tier: "orchestration" },
    { path: "POST /api/router/route", price: `$${pricing.apiRouter}`, tier: "core" },
    { path: "POST /api/research/brief", price: `$${pricing.researchBrief}`, tier: "core" },
    { path: "POST /api/receipt-auditor/verify", price: `$${pricing.receiptAuditor}`, tier: "core" },
    { path: "POST /api/refund-arbiter/evaluate", price: `$${pricing.refundArbiter}`, tier: "trust" },
    { path: "POST /api/budget-allocator/run", price: `$${pricing.budgetAllocator}`, tier: "enterprise" },
    { path: "POST /api/settlement-graph/next", price: `$${pricing.settlementGraph}`, tier: "intelligence" },
    { path: "POST /api/quality-monitor/probe", price: `$${pricing.qualityMonitor}`, tier: "intelligence" },
    { path: "POST /api/evidence-locker/export", price: `$${pricing.evidenceLocker}`, tier: "enterprise" },
    { path: "POST /api/agent-escrow", price: `$${pricing.agentEscrow}`, tier: "enterprise" },
    { path: "POST /api/merchant-trust/score", price: `$${pricing.merchantTrust}`, tier: "tier1" },
    { path: "POST /api/mandate/compile", price: `$${pricing.mandateCompile}`, tier: "tier1" },
    { path: "POST /api/rail-optimizer/route", price: `$${pricing.railOptimizer}`, tier: "tier1" },
    { path: "POST /api/compliance/ledger", price: `$${pricing.complianceLedger}`, tier: "tier1" },
    { path: "POST /api/dispute/resolve", price: `$${pricing.disputeResolve}`, tier: "tier1" },
    { path: "POST /api/quality-escrow/settle", price: `$${pricing.qualityEscrow}`, tier: "tier1" },
    { path: "POST /api/quality-escrow/semantic-settle", price: `$${pricing.qualityEscrowSemantic}`, tier: "tier1" },
    { path: "POST /api/mandate/diff", price: `$${pricing.mandateDiff}`, tier: "tier1" },
    { path: "POST /api/merchant-trust/certify", price: `$${pricing.merchantCertify}`, tier: "tier1" },
    { path: "POST /api/trust-network/buyer-gate", price: `$${pricing.buyerGate}`, tier: "tier1" },
    { path: "POST /api/trust-network/transaction-auth", price: `$${pricing.transactionAuth}`, tier: "tier1" },
    { path: "POST /api/escrow/metered/open", price: `$${pricing.escrowOpen}`, tier: "enterprise" },
    { path: "POST /api/escrow/metered/charge", price: `$${pricing.escrowCharge}`, tier: "enterprise" },
    { path: "POST /api/escrow/metered/close", price: `$${pricing.escrowClose}`, tier: "enterprise" },
    { path: "POST /api/mcp/tools/call", price: `$${pricing.mcpCall}`, tier: "core" },
    { path: "GET /api/dashboard/summary", price: "Free/Paid", tier: "core" },
    { path: "POST /api/pipeline/trust-v2", price: `$${pricing.pipelineTrustV2}`, tier: "tier1" },
    { path: "POST /api/trust-network/bond/slash", price: `$${pricing.bondSlash}`, tier: "tier1" },
    ...listProtocolEndpoints(),
  ];
}
